M48
; DRILL file {KiCad 6.0.8-f2edbf62ab~116~ubuntu20.04.1} date Tue 18 Oct 2022 12:22:52 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-18T12:22:52+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.8-f2edbf62ab~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.889
%
G90
G05
T1
X105.691Y-50.74
X108.689Y-50.74
T0
M30
