M48
; DRILL file {KiCad 6.0.9-8da3e8f707~117~ubuntu20.04.1} date Wed 28 Dec 2022 17:02:03 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-28T17:02:03+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~117~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.889
%
G90
G05
T1
X105.691Y-50.74
X108.689Y-50.74
T0
M30
