M48
; DRILL file {KiCad 7.0.2-6a45011f42~172~ubuntu22.04.1} date Mon 15 May 2023 14:22:38 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-15T14:22:38+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-6a45011f42~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X79.4Y-54.235
X79.4Y-60.015
T2
X74.4Y-32.0
X99.4Y-32.0
T0
M30
